use_frameworks!

platform :ios, '9.0'

target 'YJYCCustomerDetailKit_Example' do
  pod 'YJYCCustomerDetailKit', :path => '../'
  
  
  pod 'FCBaseKit', :git => 'https://github.com/Q007shi/FCBaseKit.git'
  pod 'FCCategoryOCKit', :git => 'https://github.com/Q007shi/FCCategoryOCKit.git'
  pod 'CTMediator'
  
end
