use_frameworks!

platform :ios, '9.0'

target 'YJYCCustomerDetailKit_Example' do
  pod 'YJYCCustomerDetailKit', :path => '../'

  target 'YJYCCustomerDetailKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
